DROP DATABASE IF EXISTS cyclopdb;
CREATE DATABASE cyclopdb;
USE cyclopdb;

DROP TABLE IF EXISTS `IMAGE`;
CREATE TABLE `IMAGE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `IMAGE_PATH` TEXT NOT NULL,
  `IMAGE` BLOB NOT NULL,
  PRIMARY KEY (`ID`)
);