/**
 * This class is generated by jOOQ
 */
package com.markovlabs.cyclop.model;


import com.markovlabs.cyclop.model.tables.Image;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cyclopdb extends SchemaImpl {

	private static final long serialVersionUID = 1725456890;

	/**
	 * The reference instance of <code>cyclopdb</code>
	 */
	public static final Cyclopdb CYCLOPDB = new Cyclopdb();

	/**
	 * No further instances allowed
	 */
	private Cyclopdb() {
		super("cyclopdb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Image.IMAGE);
	}
}
