/**
 * This class is generated by jOOQ
 */
package com.markovlabs.cyclop.model;


import com.markovlabs.cyclop.model.tables.Image;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cyclopdb
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cyclopdb.IMAGE
	 */
	public static final Image IMAGE = com.markovlabs.cyclop.model.tables.Image.IMAGE;
}
