/**
 * This class is generated by jOOQ
 */
package com.markovlabs.cyclop.model.tables;


import com.markovlabs.cyclop.model.Cyclopdb;
import com.markovlabs.cyclop.model.Keys;
import com.markovlabs.cyclop.model.tables.records.ImageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Image extends TableImpl<ImageRecord> {

	private static final long serialVersionUID = 428678370;

	/**
	 * The reference instance of <code>cyclopdb.IMAGE</code>
	 */
	public static final Image IMAGE = new Image();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImageRecord> getRecordType() {
		return ImageRecord.class;
	}

	/**
	 * The column <code>cyclopdb.IMAGE.ID</code>.
	 */
	public final TableField<ImageRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cyclopdb.IMAGE.IMAGE_PATH</code>.
	 */
	public final TableField<ImageRecord, String> IMAGE_PATH = createField("IMAGE_PATH", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>cyclopdb.IMAGE.IMAGE</code>.
	 */
	public final TableField<ImageRecord, byte[]> IMAGE_ = createField("IMAGE", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * Create a <code>cyclopdb.IMAGE</code> table reference
	 */
	public Image() {
		this("IMAGE", null);
	}

	/**
	 * Create an aliased <code>cyclopdb.IMAGE</code> table reference
	 */
	public Image(String alias) {
		this(alias, IMAGE);
	}

	private Image(String alias, Table<ImageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Image(String alias, Table<ImageRecord> aliased, Field<?>[] parameters) {
		super(alias, Cyclopdb.CYCLOPDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ImageRecord, Long> getIdentity() {
		return Keys.IDENTITY_IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ImageRecord> getPrimaryKey() {
		return Keys.KEY_IMAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ImageRecord>> getKeys() {
		return Arrays.<UniqueKey<ImageRecord>>asList(Keys.KEY_IMAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Image as(String alias) {
		return new Image(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Image rename(String name) {
		return new Image(name, null);
	}
}
